"""LaTeX booktabs tables (main results, baselines, ablations, per-family
breakdown, efficiency), best value bolded, mean +/- std across whatever
repeated runs (seeds/folds) share an identity.

Every function here REFUSES synthetic runs (``is_synthetic: true``): if
nothing real survives the filter, it writes a small placeholder .tex file
that says so explicitly, rather than fabricate or silently skip the table.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from lrmc.eval.metrics import bootstrap_ci


def _filter_real(runs: list[dict]) -> list[dict]:
    return [r for r in runs if not r.get("is_synthetic", True)]


def _get(d: dict, path: str, default=None):
    cur = d
    for part in path.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return default
        cur = cur[part]
    return cur


def _method_name(m: dict) -> str:
    return m.get("method") or m.get("run_name", "unknown")


def _group_by_method(runs: list[dict]) -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {}
    for r in runs:
        groups.setdefault(_method_name(r), []).append(r)
    return groups


def _fmt_mean_std(values: list[float]) -> str:
    values = [v for v in values if v is not None and v == v]  # drop None/NaN
    if not values:
        return "--"
    arr = np.array(values, dtype=float)
    if len(arr) == 1:
        return f"{arr[0]:.3f}"
    ci = bootstrap_ci(arr, n_boot=200)
    return f"{ci['mean']:.3f} $\\pm$ {ci['std']:.3f}"


def _write_placeholder(path: str | Path, caption: str) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "% No non-synthetic runs available yet -- run the real queue "
        "(experiments/queue.yaml) on the GPU workstation and re-run `lrmc aggregate`.\n"
        f"% Table: {caption}\n"
        "% (mock/rehearsal runs are deliberately excluded here -- see "
        "docs/DECISIONS.md)\n"
    )


def _generic_metrics_table(
    groups: dict[str, list[dict]],
    metric_paths: list[tuple[str, str]],
    caption: str,
    label: str,
    higher_is_better: dict[str, bool] | None = None,
) -> str:
    higher_is_better = higher_is_better or {}
    table_data = {
        method: {path: [_get(r, path) for r in rs] for path, _ in metric_paths}
        for method, rs in groups.items()
    }

    best = {}
    for path, _ in metric_paths:
        want_max = higher_is_better.get(path, True)
        means = {}
        for m in table_data:
            vals = [v for v in table_data[m][path] if v is not None and v == v]
            means[m] = np.mean(vals) if vals else (-np.inf if want_max else np.inf)
        best[path] = max(means, key=means.get) if want_max else min(means, key=means.get)

    lines = [
        "% Auto-generated by lrmc.aggregate.tables -- do not hand-edit.",
        "\\begin{table}[t]",
        "\\centering",
        "\\begin{tabular}{l" + "c" * len(metric_paths) + "}",
        "\\toprule",
        "Method & " + " & ".join(lbl for _, lbl in metric_paths) + " \\\\",
        "\\midrule",
    ]
    for method in sorted(table_data.keys()):
        cells = []
        for path, _ in metric_paths:
            txt = _fmt_mean_std(table_data[method][path])
            if best[path] == method and txt != "--":
                txt = f"\\textbf{{{txt}}}"
            cells.append(txt)
        method_esc = method.replace("_", "\\_")
        lines.append(f"{method_esc} & " + " & ".join(cells) + " \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        f"\\caption{{{caption}}}",
        f"\\label{{tab:{label}}}",
        "\\end{table}",
    ]
    return "\n".join(lines)


_MAIN_METRICS = [
    ("closed_set.accuracy", "Accuracy"),
    ("closed_set.macro_f1", "Macro-F1"),
    ("open_set.auroc", "AUROC"),
    ("open_set.aupr", "AUPR"),
    ("open_set.fpr_at_95tpr", "FPR@95TPR"),
    ("open_set.unknown_detection_rate", "UDR"),
    ("open_set.known_false_rejection_rate", "FRR"),
    ("oscr.oscr_auc", "OSCR-AUC"),
]
_HIGHER_IS_BETTER = {
    "open_set.fpr_at_95tpr": False,
    "open_set.known_false_rejection_rate": False,
}


def generate_main_results_table(runs: list[dict], out_path: str | Path) -> None:
    real = [r for r in _filter_real(runs) if "ablation" not in r.get("run_name", "")]
    if not real:
        _write_placeholder(out_path, "Main results (LRMC vs. baselines)")
        return
    groups = _group_by_method(real)
    tex = _generic_metrics_table(
        groups, _MAIN_METRICS, "Main results: LRMC vs. baselines", "main_results", _HIGHER_IS_BETTER
    )
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(tex)


def generate_ablation_table(runs: list[dict], out_path: str | Path) -> None:
    real = [r for r in _filter_real(runs) if r.get("run_name", "").startswith("ablation_")]
    if not real:
        _write_placeholder(out_path, "Ablation study")
        return
    groups = _group_by_method(real)
    tex = _generic_metrics_table(
        groups, _MAIN_METRICS, "Ablation study", "ablations", _HIGHER_IS_BETTER
    )
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(tex)


def generate_efficiency_table(runs: list[dict], out_path: str | Path) -> None:
    real = _filter_real(runs)
    if not real:
        _write_placeholder(out_path, "Efficiency comparison")
        return
    metric_paths = [
        ("efficiency.total_params", "Params"),
        ("efficiency.approx_flops", "Approx.\\ FLOPs"),
        ("efficiency.mean_latency_s_per_sample", "Latency (s/sample)"),
        ("efficiency.throughput_samples_per_s", "Throughput (samples/s)"),
        ("efficiency.peak_memory_bytes", "Peak mem.\\ (bytes)"),
    ]
    higher_better = {
        "efficiency.total_params": False,
        "efficiency.approx_flops": False,
        "efficiency.mean_latency_s_per_sample": False,
        "efficiency.throughput_samples_per_s": True,
        "efficiency.peak_memory_bytes": False,
    }
    groups = _group_by_method(real)
    tex = _generic_metrics_table(
        groups, metric_paths, "Efficiency comparison", "efficiency", higher_better
    )
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(tex)


def generate_per_family_table(runs: list[dict], out_path: str | Path) -> None:
    """Per-class precision/recall/F1 for the main LRMC run (first non-ablation,
    non-baseline real run found)."""
    real = [
        r
        for r in _filter_real(runs)
        if r.get("method") is None and "ablation" not in r.get("run_name", "")
    ]
    if not real:
        _write_placeholder(out_path, "Per-family breakdown (main LRMC run)")
        return
    run = real[0]
    report = _get(run, "closed_set.per_class_report", {})
    families = [k for k in report if k not in ("accuracy", "macro avg", "weighted avg")]
    if not families:
        _write_placeholder(out_path, "Per-family breakdown (main LRMC run)")
        return
    lines = [
        "% Auto-generated by lrmc.aggregate.tables -- do not hand-edit.",
        "\\begin{table}[t]",
        "\\centering",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Family & Precision & Recall & F1 \\\\",
        "\\midrule",
    ]
    for fam in families:
        row = report[fam]
        fam_esc = fam.replace("_", "\\_")
        lines.append(
            f"{fam_esc} & {row['precision']:.3f} & {row['recall']:.3f} & {row['f1-score']:.3f} \\\\"
        )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        f"\\caption{{Per-family breakdown, run {run.get('run_name', '?')}}}",
        "\\label{tab:per_family}",
        "\\end{table}",
    ]
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text("\n".join(lines))


def generate_all_tables(runs: list[dict], out_dir: str | Path) -> None:
    out_dir = Path(out_dir)
    generate_main_results_table(runs, out_dir / "main_results.tex")
    generate_ablation_table(runs, out_dir / "ablations.tex")
    generate_efficiency_table(runs, out_dir / "efficiency.tex")
    generate_per_family_table(runs, out_dir / "per_family.tex")
